// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function App(Props) {
  var match = React.useState((function () {
          return /* [] */0;
        }));
  var setTodos = match[1];
  var match$1 = React.useState((function () {
          return "";
        }));
  var setNewTodo = match$1[1];
  var newTodo = match$1[0];
  var addTodo = function (param) {
    Curry._1(setTodos, (function (todos) {
            return /* :: */[
                    /* record */[
                      /* text */newTodo,
                      /* completed */false
                    ],
                    todos
                  ];
          }));
    return Curry._1(setNewTodo, (function (param) {
                  return "";
                }));
  };
  return React.createElement("div", {
              style: {
                display: "flex",
                alignItems: "center",
                flex: "1",
                flexDirection: "column",
                justifyContent: "center"
              }
            }, React.createElement("div", undefined, React.createElement("input", {
                      value: newTodo,
                      onKeyDown: (function (evt) {
                          if (evt.key === "Enter") {
                            return addTodo(/* () */0);
                          } else {
                            return 0;
                          }
                        }),
                      onChange: (function ($$event) {
                          return Curry._1(setNewTodo, $$event.target.value);
                        })
                    }), React.createElement("button", {
                      onClick: addTodo
                    }, "Submit")), React.createElement("div", undefined, $$Array.of_list(List.mapi((function (index, todo) {
                            return React.createElement("div", {
                                        key: String(index)
                                      }, todo[/* text */0]);
                          }), match[0]))));
}

var make = App;

exports.make = make;
/* react Not a pure module */
