// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");

var idRef = /* record */[/* contents */0];

function App(Props) {
  var match = React.useState((function () {
          return /* [] */0;
        }));
  var setTodos = match[1];
  var todos = match[0];
  var match$1 = React.useState((function () {
          return "";
        }));
  var setNewTodo = match$1[1];
  var newTodo = match$1[0];
  var addTodo = function (param) {
    if ($$String.trim(newTodo) !== "") {
      idRef[0] = idRef[0] + 1 | 0;
      Curry._1(setTodos, (function (todos) {
              return /* :: */[
                      /* record */[
                        /* id */idRef[0],
                        /* text */newTodo,
                        /* completed */false
                      ],
                      todos
                    ];
            }));
      return Curry._1(setNewTodo, (function (param) {
                    return "";
                  }));
    } else {
      return 0;
    }
  };
  return React.createElement("div", {
              style: {
                display: "flex",
                alignItems: "center",
                flex: "1",
                flexDirection: "column",
                justifyContent: "center"
              }
            }, React.createElement("div", undefined, React.createElement("input", {
                      value: newTodo,
                      onKeyDown: (function (evt) {
                          if (evt.key === "Enter") {
                            return addTodo(/* () */0);
                          } else {
                            return 0;
                          }
                        }),
                      onChange: (function ($$event) {
                          return Curry._1(setNewTodo, $$event.target.value);
                        })
                    }), React.createElement("button", {
                      onClick: addTodo
                    }, "Submit")), React.createElement("div", undefined, $$Array.of_list(List.map((function (todo) {
                            return React.createElement("div", {
                                        key: String(todo[/* id */0]),
                                        style: {
                                          cursor: "pointer",
                                          display: "grid",
                                          maxWidth: "300px",
                                          gridTemplateColumns: "auto 1fr"
                                        },
                                        onClick: (function (param) {
                                            var id = todo[/* id */0];
                                            var todos$1 = List.map((function (item) {
                                                    var match = item[/* id */0] === id;
                                                    if (match) {
                                                      return /* record */[
                                                              /* id */item[/* id */0],
                                                              /* text */item[/* text */1],
                                                              /* completed */!item[/* completed */2]
                                                            ];
                                                    } else {
                                                      return item;
                                                    }
                                                  }), todos);
                                            return Curry._1(setTodos, (function (param) {
                                                          return todos$1;
                                                        }));
                                          })
                                      }, React.createElement("input", {
                                            checked: todo[/* completed */2],
                                            readOnly: true,
                                            type: "checkbox"
                                          }), todo[/* text */1]);
                          }), todos))));
}

var make = App;

exports.idRef = idRef;
exports.make = make;
/* react Not a pure module */
